#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

path=$1
ip=$2
username=$3
path_to_key=$4

#check if parameters less than 4
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	scp -o StrictHostKeyChecking=no -i $path_to_key $path $username@$ip:~/
fi
