#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

# Installation process
sudo apt-get -y install nginx


# Edting the the default web page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
