#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page..
# Installation process
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

sudo service nginx start

# Edting the the default web page
sudo sed -i '/^[^#]*server_name/ a \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

sudo service nginx restart
