#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page..

sudo ./1-install_nginx_web_server

# Add a redirection
sudo sed -i '/^\s*server_name\s*[^#]/ a \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

# Restart the server
sudo service nginx restart
