#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page..
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '46i ^/rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
