#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

#variables
REDIRECT="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com/;\n\t}"
ERROR404="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

# Installation process
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

# Edting the the default web page
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/listen 80 default_server;/a $REDIRECT" /etc/nginx/sites-available/default

# Adding a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "/listen 80 default_server;/a $ERROR404" /etc/nginx/sites-available/default

# Restarting the server
sudo service nginx restart
