#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures
# a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        add_header X-Served-By $(hostname);
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
