#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures
# a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
