#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# Installation process
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

configs="server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
	
	add_header X-Served-By $HOSTNAME;
	
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}"

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
echo "$configs" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart

