#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

configs="frontend http_front
	bind *:80
	mode http
	default_backend http_back

backend http_back
	balance roundrobin
	mode http
	server 433785-web-01 18.234.145.174:80 check
	server 433785-web-02 34.202.158.120:80 check"

echo "$configs" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo service haproxy restart
