#!/usr/bin/env bash
# configure a new ubuntu machine to run nginx on it

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
