#!/usr/bin/env	bash
# configure a new ubuntu machine to run nginx on it
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
