#!/usr/bin/env bash
# MAHMUD MALEK

case $1 in
    start)
            nohup bash -c 'while true; do echo "I am alive!" >> /tmp/my_process; sleep 2; done' &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        ;;
    stop)
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"

        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi
        nohup bash -c 'while true; do echo "I am alive!" >> /tmp/my_process; sleep 2; done' &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
