#!/usr/bin/env bash
# Using awk to count occurrences of each unique combination of IP and HTTP status code,
# then sorting and displaying the data in the specified format

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
