#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

# Initializing variables
hours=-1
minutes=60

# Loop to display time in 12-hour format
while [ $hours -lt 13 ]; do
    if [ $minutes -eq 60 ]; then
        ((minutes = 0))
        ((hours++))
		echo "Hour: $hours"
	else
		echo "$minutes"
    fi

    ((minutes++))
done
