#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
minutes=1
echo "Hour: 0"
while [ $hours -lt 12 ]
do
	
	if [ $minutes -eq 60 ]
	then
		((minutes = 0))
		((hours++))
		echo "Hour: $hours"
	else
		echo "$minutes"
	fi
	((minutes++))
done
